var movie_list = [
    "The Shawshank Redemption",
    "The Godfather",
    "The Dark Knight",
    "Schindler's List",
    "Pulp Fiction",
    "The Lord of the Rings: The Return of the King",
    "Fight Club",
    "The Lord of the Rings: The Fellowship of the Ring",
    "Star Wars: Episode V - The Empire Strikes Back",
    "Forrest Gump",
    "Inception",
    "The Lord of the Rings: The Two Towers",
    "One Flew Over the Cuckoo's Nest",
    "Goodfellas",
    "The Matrix",
    "Seven Samurai",
    "Star Wars: Episode IV - A New Hope",
    "City of God",
    "Se7en",
    " The Silence of the Lambs",
    "The Usual Suspects",
    "Leon The professional",
    "Saving Private Ryan",
    "American History X",
    "Interstellar",
    "The Green Mile",
    "Untouchable",
    "The Pianist",
    "The Departed",
    "Back to the Future",
    "Whiplash",
    "Gladiator",
    "Memento",
    "The Prestige",
    "The Lion King",
    "Alien",
    "The Lives of Others",
    "Django Unchained",
    "The Shining",
    "WALL·E",
    "The Dark Knight Rises",
    "American Beauty",
    "Vertigo",
    "Star Wars: Episode VI - Return of the Jedi",
    "Reservoir Dogs",
    "Braveheart",
    "Requiem for a Dream",
    "A Clockwork Orange",
    "Taxi Driver",
    "Eternal Sunshine of the Spotless Mind",
    "Toy Story 3",
    "2001: A Space Odyssey",
    "Snatch",
    "Inglourious Basterds",
    "Monty Python and the Holy Grail",
    "L.A. Confidential",
    "Scarface",
    "Arrival",
    "The Hunt",
    "A Separation",
    "Good Will Hunting",
    "Batman Begins",
    "Up",
    "Die Hard",
    "Heat",
    "Inside Out",
    "Room",
    "A Beautiful Mind",
    "Warrior",
    "V for Vendetta",
    "The Wolf of Wall Street",
    "Gran Torino",
    "Dial M for Murder",
    "The Big Lebowski",
    "Fargo",
    "Finding Nemo",
    "The Sixth Sense",
    "The Thing",
    "How to Train Your Dragon",
    "No Country for Old Men",
    "Into the Wild",
    "Kill Bill: Vol. 1",
    "Mary and Max",
    "Gone Girl",
    "There Will Be Blood",
    "Star Wars: The Force Awakens",
    "Life of Brian",
    "Rush",
    "Shutter Island",
    "Spotlight",
    "Mad Max: Fury Road",
    "12 Years a Slave",
    "The Grand Budapest Hotel",
    "Million Dollar Baby",
    "Jurassic Park",
    "The Truman Show",
    "Before Sunrise",
    "The Bourne Ultimatum",
    "Harry Potter and the Deathly Hallows: Part 2",
    "Donnie Darko",
    "zootopia",
    "Monsters, Inc.",
    "The Terminator",
    "Prisoners",
    "Groundhog Day",
    "Catch Me If You Can",
    "Jaws",
    "Sin City",
    "The Help",
    "The Imitation Game",
    "The Basketball Diaries",
    "Harry Potter and the Sorcerer's Stone",
    "Harry Potter and the Chamber of Secrets",
    "Dumb and Dumber",
    "The Butterfly Effect",
    "The Girl With The Dragon Tattoo",
    "8 Mile",
    "The Place Beyond The Pines",
    "Titanic",
    "The Great Gatsby",
    "Blood Diamond",
    "The Aviator",
    "What's Eating Gilbert Grape",
    "The Revenant",
    "The King's Speech",
    "Silver Linings Playbook",
    "Horrible Bosses",
    "The Artist",
    "The Hurt Locker",
    "Disconnect",
    "Dallas Buyers Club",
    "Her",
    "Kick-Ass",
    "Superbad",
    "Skyfall",
    "Moneyball",
    "The Avengers",
    "21 Jump Street",
    "American History X",
    "Nightcrawler",
    "Lone Survivor",
    "The Lego Movie",
    "Captain America: The Winter Soldier",
    "Mud",
    "Dawn of the Planet of the Apes",
    "Edge of Tomorrow",
    "The Equalizer",
    "Guardians of the Galaxy",
    "The Curious Case of Benjamin Button",
    "The Hangover",
    "Ratatouille",
    "Star Trek",
    "Black Swan",
    "Midnight in Paris",
    "127 Hours",
    "Elysium",
    "Oblivion",
    "Looper",
    "District 9",
    "World War Z",
    "Bridge of Spies",
    "I, Robot",
    "The Pursuit of Happyness",
    "Sherlock Holmes",
    "Wanted",
    "Filth",
    "Casino Royale",
    "The Fighter",
    "The Town",
    "50/50",
    "Cast Away",
    "The Social Network",
    "Straight Outta Compton",
    "The Martian",
    "The Double",
    "Citizenfour",
    "Snowden",
    "The Accountant",
    "Deepwater Horizon",
    "The Magnificent Seven",
    "Sully",
    "Flight",
    "Scott Pilgrim vs. the World",
    "Suicide Squad",
    "Hell or High Water",
    "War Dogs",
    "Star Trek Beyond",
    "Lights Out",
    "The Infiltrator",
    "The Da Vinci Code",
    "X-Men: Apocalypse",
    "Free State of Jones",
    "Malcolm X",
    "The Man Who Knew Infinity",
    "Theory of Everything",
    "RED",
    "Contagion",
    "Demolition",
    "Batman v Superman: Dawn of Justice",
    "Green Room",
    "The Polar Express",
    "Miracles from Heaven",
    "Kung Fu Panda 2",
    "Colonia",
    "10 Cloverfield Lane",
    "This Is the End",
    "Ted",
    "Drive",
    "Zero Dark Thirty",
    "Mr. Brooks",
    "Star Trek Into Darkness",
    "Now You See Me",
    "Despicable Me 2",
    "The Spectacular Now",
    "Short Term 12",
    "Fruitvale Station",
    "Nebraska",
    "The World's End",
    "Saving Mr. Banks",
    "Boyhood",
    "Mean Creek",
    "End Of Watch",
    "Let's Be Cops",
    "The Witch",
    "Deadpool",
    "Zero Days",
    "Take Shelter",
    "The Nice Guys",
    "Cars",
    "The Lorax",
    "Ice Age",
    "Catfish",
    "13 Hours",
    "John Wick",
    "Star Wars: Episode VII - The Force Awakens",
    "Concussion",
    "The Hateful Eight",
    "The Big Short",
    "Carol",
    "Brooklyn",
    "Creed",
    "The Lobster",
    "Trumbo",
    "Steve Jobs",
    "Legend",
    "The Intern",
    "Sicario",
    "Dope",
    "Furious 7",
    "Particle Fever",
    "Kingsman: The Secret Service",
    "Ex Machina",
    "McFarland, USA",
    "American Sniper",
    "Selma",
    "Still Alice",
    "Camp X-Ray",
    "The Water Diviner",
    "'71",
    "Munich",
    "Big Hero 6",
    "Kill the Messenger",
    "Birdman",
    "Fury",
    "Ghostbusters",
    "The Drop",
    "A Brief History of Time",
    "Predestination",
    "Ray",
    "Million Dollar Arm",
    "Maleficent",
    "Chef",
    "The Fault in Our Stars",
    "Roger Dodger",
    "Adventureland",
    "Zombieland",
    "Tracks",
    "Juno",
    "The Terminal",
    "Snowpiercer",
    "The Secret Life of Walter Mitty",
    "Philomena",
    "Flipped",
    "The Book Thief",
    "Gravity",
    "Thor: The Dark World",
    "Milk",
    "About Time",
    "The Butler",
    "We're the Millers",
    "Monsters University",
    "Pacific Rim",
    "Before Midnight",
    "Chasing Ice",
    "Stuck in Love",
    "The Croods",
    "Still Mine",
    "Iron Man 3",
    "Hunger",
    "The Longest Day",
    "42",
    "Crash",
    "Natural Born Killers",
    "Training Day",
    "Almost Famous",
    "The Exorcist",
    "The Ring",
    "The Untouchables",
    "Life Of Pi",
    "Chicken Run",
    "The Perks of Being a Wallflower",
    "TPB AFK: The Pirate Bay Away from Keyboard",
    "Argo",
    "Seven Psychopaths",
    "Before Sunset",
    "Kill Bill: Vol. 2",
    "Dredd",
    "Miller's Crossing",
    "Cloud Atlas",
    "Dead Poets Society",
    "It's Kind of a Funny Story",
    "Pitch Perfect",
    "Enter the Dragon",
    "Capote",
    "Limitless",
    "American Psycho",
    "Lawless",
    "The Ghost Writer",
    "Hotel Rwanda",
    "Flags of Our Fathers",
    "The Boy in the Striped Pajamas",
    "Brave",
    "Cloverfield",
    "Pineapple Express",
    "Safety Not Guaranteed",
    "The Bucket List",
    "Boyz n the Hood",
    "Edward Scissorhands",
    "Rango",
    "Lord of War",
    "Up in the Air",
    "Prometheus",
    "Weekend",
    "Platoon",
    "The Italian Job",
    "Borat: Cultural Learnings of America for Make Benefit Glorious Nation of Kazakhstan",
    "Tucker and Dale vs Evil",
    "Seven Pounds",
    "The Raid: Redemption",
    "Men in Black",
    "Man on the Moon",
    "The Cabin in the Woods",
    "Death at a Funeral",
    "The Blind Side",
    "Valkyrie",
    "Collateral",
    "Unleashed",
    "The 40-Year-Old Virgin",
    "Easy A",
    "Shooter",
    "Despicable Me",
    "Chronicle",
    "Rio",
    "Food, Inc.",
    "Friday",
    "Hugo",
    "Megamind",
    "Pi",
    "American Gangster",
    "Jerry Maguire",
    "ip Man",
    "The Machinist",
    "Perfume: The Story of a Murderer",
    "Hard Candy",
    "The Ides of March",
    "Crazy, Stupid, Love.",
    "Jane Eyre",
    "Knocked Up",
    "Saw",
    "The Notebook",
    "Mr. Nobody",
    "Revolutionary Road",
    "The Deer Hunter",
    "Rain Man",
    "The Insider",
    "Body of Lies",
    "Southpaw",
    "Avengers: Age of Ultron"
];
console.log(movie_list.length);
module.exports = movie_list;
