var movie_list = [
    "The Shawshank Redemption",
    "The Godfather",
    "The Dark Knight",
    "Schindler's List",
    "Pulp Fiction",
    "The Lord of the Rings: The Return of the King",
    "Fight Club",
    "The Lord of the Rings: The Fellowship of the Ring",
    "Star Wars: Episode V - The Empire Strikes Back",
    "Forrest Gump",
    "Inception",
    "The Lord of the Rings: The Two Towers",
    "One Flew Over the Cuckoo's Nest",
    "Goodfellas",
    "The Matrix",
    "Seven Samurai",
    "Star Wars: Episode IV - A New Hope",
    "City of God",
    "Se7en",
    " The Silence of the Lambs",
    "The Usual Suspects",
    "Leon The professional",
    "Saving Private Ryan",
    "American History X",
    "Interstellar",
    "The Green Mile",
    "Untouchable",
    "The Pianist",
    "The Departed",
    "Back to the Future",
    "Whiplash",
    "Gladiator",
    "Memento",
    "The Prestige",
    "The Lion King",
    "Alien",
    "The Lives of Others",
    "Django Unchained",
    "The Shining",
    "WALL·E",
    "The Dark Knight Rises",
    "American Beauty",
    "Vertigo",
    "Star Wars: Episode VI - Return of the Jedi",
    "Reservoir Dogs",
    "Braveheart",
    "Requiem for a Dream",
    "A Clockwork Orange",
    "Taxi Driver",
    "Eternal Sunshine of the Spotless Mind",
    "Toy Story 3",
    "2001: A Space Odyssey",
    "Snatch",
    "Inglourious Basterds",
    "Monty Python and the Holy Grail",
    "L.A. Confidential",
    "Scarface",
    "Arrival",
    "The Hunt",
    "A Separation",
    "Good Will Hunting",
    "Batman Begins",
    "Up",
    "Die Hard",
    "Heat",
    "Inside Out",
    "Room",
    "A Beautiful Mind",
    "Warrior",
    "V for Vendetta",
    "The Wolf of Wall Street",
    "Gran Torino",
    "Dial M for Murder",
    "The Big Lebowski",
    "Fargo",
    "Finding Nemo",
    "The Sixth Sense",
    "The Thing",
    "How to Train Your Dragon",
    "No Country for Old Men",
    "Into the Wild",
    "Kill Bill: Vol. 1",
    "Mary and Max",
    "Gone Girl",
    "There Will Be Blood",
    "Star Wars: The Force Awakens",
    "Life of Brian",
    "Rush",
    "Shutter Island",
    "Spotlight",
    "Mad Max: Fury Road",
    "12 Years a Slave",
    "The Grand Budapest Hotel",
    "Million Dollar Baby",
    "Jurassic Park",
    "The Truman Show",
    "Before Sunrise",
    "The Bourne Ultimatum",
    "Harry Potter and the Deathly Hallows: Part 2",
    "Donnie Darko",
    "zootopia",
    "Monsters, Inc.",
    "The Terminator",
    "Prisoners",
    "Groundhog Day",
    "Catch Me If You Can",
    "Jaws",
    "Sin City",
    "The Help",
    "The Imitation Game",
    "The Basketball Diaries",
    "Harry Potter and the Sorcerer's Stone",
    "Harry Potter and the Chamber of Secrets",
    "Dumb and Dumber",
    "The Butterfly Effect",
    "The Girl With The Dragon Tattoo",
    "8 Mile",
    "The Place Beyond The Pines",
    "Titanic",
    "The Great Gatsby",
    "Blood Diamond",
    "The Aviator",
    "What's Eating Gilbert Grape",
    "The Revenant",
    "The King's Speech",
    "Silver Linings Playbook",
    "Horrible Bosses",
    "The Artist",
    "The Hurt Locker",
    "Disconnected",
    "Dallas Buyers Club",
    "Her",
    "Kick-Ass",
    "Superbad",
    "Skyfall",
    "Moneyball",
    "The Avengers",
    "21 Jump Street",
    "American History X",
    "Nightcrawler",
    "Lone Survivor",
    "The Lego Movie",
    "Captain America: The Winter Soldier",
    "Mud",
    "Dawn of the Planet of the Apes",
    "Edge of Tomorrow",
    "The Equalizer",
    "Guardians of the Galaxy",
    "The Curious Case of Benjamin Button",
    "The Hangover",
    "Ratatouille",
    "Star Trek",
    "Black Swan",
    "Midnight in Paris",
    "127 Hours",
    "Elysium",
    "Oblivion",
    "Looper",
    "District 9",
    "World War Z",
    "Bridge of Spies",
    "I, Robot",
    "The Pursuit of Happyness",
    "Sherlock Holmes",
    "Wanted",
    "Filth",
    "Casino Royale",
    "The Fighter",
    "The Town",
    "50/50",
    "Cast Away",
    "The Social Network",
    "Straight Outta Compton",
    "The Martian"
];

module.exports = movie_list;